# Generated by Django 3.0.8 on 2020-07-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='token',
        ),
    ]
